### PR TITLE
Improve meson build system

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi @casasfernando I made some cleanup to your project structure, especially with meson files.

Let me know if you have any questions.

### CODE REVIEW

**Review by casasfernando — APPROVED** [review]
Thanks for this great contribution, I'm merging it now and will apply similar changes to my other projects. :tada:

**Comment by NathanBnm** [comment]
@casasfernando do not hesitate to create a PR on your other projects and ask me for review if you want me to check 😄 

Regarding translation files. It's better not to add them for untranslated languages. Translators have to add their language code themselves into `LINGUAS` files and run the language files update commands to generate the associated `.po` files 
and translate them. This way the translation files are always matching the last version. Adding a blank translation file may suggest that there is already a translation for that language

You could add a translator contributing guide inside the translations folder and link it to the appdata "Translate" link.
A good example is https://github.com/ryonakano/reco/blob/main/po/README.md

**Comment by casasfernando** [comment]
Great explanation again. I will merge the second commit as well.
Just one question: for the polish translation in your commit I see the chaset changed from UTF-8 to ASCII, are you sure this is correct? I know that for spanish we need UTF-8 due to the special characters and I would suspect this may be the same for polish.

**Comment by NathanBnm** [comment]
> Great explanation again. I will merge the second commit as well. Just one question: for the polish translation in your commit I see the chaset changed from UTF-8 to ASCII, are you sure this is correct? I know that for spanish we need UTF-8 due to the special characters and I would suspect this may be the same for polish.

You're right I didn't noticed that the charset was affected when I regenerated the file 👀 
Polish contains accentuated letters so we need UTF-8 for it

**Comment by NathanBnm** [comment]
Just made the fix 😉

**Comment by casasfernando** [comment]
Cool will proceed with the merge.
BTW you mentioned the polish file was not properly format, do you mind pointing me out those errors so I can learn and detect this in the future?

**Comment by NathanBnm** [comment]
There was a mismatch between the `.pot` file and the Polish `.po` file headers. You can always refer to the translation template file in order to check.

Usually when you add a language as a translator you can add the language code to the `LINGUAS` file and use the command line (`ninja com.github.casasfernando.wingpanel-indicator-weather-update-po`)  to generate the associated `.po` file.

In this case the translator didn't use this method so the file header was altered (See ee458caccbc6229d91bb9c678c49ef5b3852cda4).

Here is the difference after regenerating the file:

Before
```po
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: POEditor.com\n"
"Project-Id-Version: Wingpanel Weather\n"
"Language: pl\n"
```
After
```po
# Polish translations for com.github.casasfernando.wingpanel-indicator-weather package.
# Copyright (C) 2021 THE com.github.casasfernando.wingpanel-indicator-weather'S COPYRIGHT HOLDER
# This file is distributed under the same license as the com.github.casasfernando.wingpanel-indicator-weather package.
# Automatically generated, 2021.
#
msgid ""
msgstr ""
"Project-Id-Version: com.github.casasfernando.wingpanel-indicator-weather\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-12-01 22:54+0100\n"
"PO-Revision-Date: 2021-12-01 22:54+0100\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2);\n"
```

Translators can also manually copy the content of the translation template file but it's easiest to use the automated way which completes the file headers automatically. Usually translators just have to replace `Automatically generated` by their name and e-mail.

Hope I have answered to your concerns.

**Comment by NathanBnm** [comment]
I assume this can be closed right?

**Comment by casasfernando** [comment]
Brilliant, got it now!
If you find more things that can be improved in any of my projects, please keep the feedback coming as I'm still learning as mentioned in the README files. :smile: 
All changes merged, closing the PR.

Thanks.

**Pull request closed without merging**
