### PR TITLE
Make app indicator-only

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! I ran into problems trying to add the French translation. Since the project contains both an indicator and an application it is impossible to translate both correctly because of the `-DGETTEXT_PACKAGE` argument which can point only one of these.

I found a solution by using a Gtk.Dialog component for settings instead of calling a dedicated application.

I also removed the "Show indicator" options from settings because if you hide the indicator you don't have access to settings anymore to put it back.

Morover I added a call to update weather data when changing units, so they can be reflected immediatly inside the indicator.

Everything is working fine on my side except that clicking the "Open settings" button multiple times opens multiple settings dialogs. I didn't figured out how to open the dialog only if it hasn't been instanciated before. Any idea?

Let me know what you think about these changes. This will definitely help fo translations.

### CODE REVIEW

**Comment by casasfernando** [comment]
I just double checked because I was sure translations were working for both, indicator and settings app, at least *before* https://github.com/casasfernando/wingpanel-indicator-weather/commit/e8402804805e27505fbcff8edaa673207f465c40.

These are screenshots with both working with spanish translations:

image
indicator_es

So I would review which change from https://github.com/casasfernando/wingpanel-indicator-weather/commit/e8402804805e27505fbcff8edaa673207f465c40 caused this new issue.
Will most likely look into this during the weekend.

Thanks.

**Comment by NathanBnm** [comment]
Oh okay I'll check on my side as well

**Comment by casasfernando** [comment]
> I also removed the "Show indicator" options from settings because if you hide the indicator you don't have access to settings anymore to put it back.

There is no need to do this if we keep the settings app as it is today. The user can easily access the indicator settings again from the Applications menu and re-enable the indicator if needed.
I think this is a good thing because it allows to easily control panel clutter anytime if needed.

> Morover I added a call to update weather data when changing units, so they can be reflected immediatly inside the indicator.

This was already implemented:

https://github.com/casasfernando/wingpanel-indicator-weather/blob/46cc15b5e31f5d3bfa8fde03e86fb09d3ea0ffa4/src/Indicator.vala#L181-L184


Thanks!

**Comment by casasfernando** [comment]
Another thing I observed is that you "marked for translation" some things that I'm not sure they need to be translated like some unit names (eg: Beaufort (bft), Hectopascal (hPa), Celsius (ºC)).

I don't think their names change across languages. Do they change in french for example?

**Comment by NathanBnm** [comment]
You're right :smile: I'm closing this

**Pull request closed without merging**
